### PR TITLE
Update for new worlflow

### PR DESCRIPTION
**Pull request by chuckwagoncomputing**

### CODE REVIEW

**Comment by chuckwagoncomputing** [comment]
I didnt mean to

**Comment by rusefillc** [comment]
@chuckwagoncomputing i've reopened

**Comment by chuckwagoncomputing** [comment]
I meant that I didn't mean to open the pull request, but it's all good now.

**Comment by chuckwagoncomputing** [comment]
It's failing on my main and I'm not sure why.
https://github.com/chuckwagoncomputing/fw-custom-example/actions/runs/7946709274/job/21694740496

**Comment by chuckwagoncomputing** [comment]
seems to be related to https://github.com/rusefi/rusefi/commit/c8e779753a9f1c4d8dfc3b96c1cea01d21d67123

**Comment by rusefillc** [comment]
@chuckwagoncomputing i kind of know this issue. i've just added new calibration field but not all jobs do proper update. Simulator for instance gails every time once for each valibration meta change

**Comment by chuckwagoncomputing** [comment]
Also I need to rework the workflow to be PR and non-main-branch friendly, but that's a separate issue.

**Pull request merged**
